'use client';
import Link from 'next/link';
import Image from 'next/image';

export default function Assignment2() {
  return (
    <>
      <div className="text-center py-4 bg-info bg-gradient">
        <h1 className="text-white mb-3">Indus University | Assignment-2</h1>
        <h4 className="text-white my-2">Engineering Graphics</h4>
        <p className="text-white mb-0">CSE Section</p>
      </div>

      <div className="container-fluid">
        <div className="row min-vh-100">
          {/* Sidebar */}
          <div className="col-lg-3 px-0">
            <div className="card h-100 rounded-0 border-end position-sticky top-0">
              <div className="card-body d-flex flex-column align-items-center">
                <h3 className="card-title text-center mb-4">Course Plan:</h3>
                <div className="d-flex flex-column w-100">
                  <Link href="/automobile" className="nav-link py-3 border-bottom text-center">
                    Automobile Engineering
                  </Link>
                  <Link href="/calculus" className="nav-link py-3 border-bottom text-center">
                    Engineering Calculus
                  </Link>
                  <Link href="/ec" className="nav-link py-3 border-bottom text-center">
                    Engineering Chemistry
                  </Link>
                  <Link href="/es" className="nav-link py-3 border-bottom text-center">
                    Environmental Science
                  </Link>
                  <Link href="/boe" className="nav-link py-3 border-bottom text-center">
                    Basic of Energy
                  </Link>
                  <Link href="/tcss" className="nav-link py-3 border-bottom text-center">
                    Technical Communication
                  </Link>
                  <Link href="/eg" className="nav-link py-3 border-bottom text-center">
                    Engineering Graphics
                  </Link>
                  <Link href="/iks" className="nav-link py-3 border-bottom text-center">
                    Indian Knowledge System
                  </Link>
                </div>
              </div>
            </div>
          </div>

          {/* Main Content */}
          <div className="col-lg-9 py-4">
            <div className="card shadow">
              <div className="card-body">
                {/* Question 1 */}
                <div className="mb-5">
                  <h4 className="text-info mb-3">Question 1:</h4>
                  <p className="fw-bold mb-4">
                    Define : (i) Cycloid (ii) Hypocycloid (iii) Epicycloid (iv) Involute
                  </p>
                  <ul>
                    <li><strong>Cycloid:</strong> A cycloid is the curve traced by a point on a circle as it rolls along a straight line without slipping.</li>
                    <li><strong>Hypocycloid:</strong> A hypocycloid is a special plane curve generated by the trace of a fixed point on a small circle that rolls within a larger circle. As the radius of the larger circle is increased, the hypocycloid becomes more like the cycloid created by rolling a circle on a line.</li>
                    <li><strong>Epicycloid:</strong> An epicycloid is a plane curve created by tracing a chosen point on the edge of a circle of radius r rolling on the outside of a circle of radius R.</li>
                    <li><strong>Involute:</strong> The involute is defined as the path of a point on a straight line which rolls without slipping along the circumference of a cylinder. The involute curve will be required for the construction of gear teeth.</li>
                  </ul>
                </div>

                {/* Question 2 */}
                <div className="mb-5">
                  <h4 className="text-info mb-3">Question 2:</h4>
                  <p className="fw-bold mb-4">
                    A circle of 30 mm radius is rolling on a straight line without slip. Point P is at the point of contact between generating circle and directing line. Draw the locus of point P and name the curve.
                  </p>
                  <div className="text-center">
                    <Image
                      src="/images/a2d2.jpg"
                      alt="Diagram 2"
                      width={600}
                      height={400}
                      className="img-fluid rounded shadow-sm"
                    />
                  </div>
                </div>

                {/* Question 3 */}
                <div className="mb-5">
                  <h4 className="text-info mb-3">Question 3:</h4>
                  <p className="fw-bold mb-4">
                    Construct 3 convolution of the involute of 10 mm longline.
                  </p>
                  <div className="text-center">
                    <Image
                      src="/images/a2d3.jpg"
                      alt="Diagram 3"
                      width={600}
                      height={400}
                      className="img-fluid rounded shadow-sm"
                    />
                  </div>
                </div>

                {/* Question 4 */}
                <div className="mb-5">
                  <h4 className="text-info mb-3">Question 4:</h4>
                  <p className="fw-bold mb-4">
                    Show graphically that the hypocycloid is a straight line. When diameter of rolling circle is half of the directing circle.
                  </p>
                  <div className="text-center">
                    <Image
                      src="/images/a2d4.jpg"
                      alt="Diagram 4"
                      width={600}
                      height={400}
                      className="img-fluid rounded shadow-sm"
                    />
                  </div>
                </div>

                {/* Question 5 */}
                <div className="mb-5">
                  <h4 className="text-info mb-3">Question 5:</h4>
                  <p className="fw-bold mb-4">
                    Draw an Involute for a semi-circle of radius 25mm.
                  </p>
                  <div className="text-center">
                    <Image
                      src="/images/a2d5.jpg"
                      alt="Diagram 5"
                      width={600}
                      height={400}
                      className="img-fluid rounded shadow-sm"
                    />
                  </div>
                </div>

                {/* Question 6 */}
                <div className="mb-5">
                  <h4 className="text-info mb-3">Question 6:</h4>
                  <p className="fw-bold mb-4">
                    Construct the Archemedian Spiral of two convolutions. The largest radius is 100 mm and the smallest radius is 20 mm.
                  </p>
                  <div className="text-center">
                    <Image
                      src="/images/a2d6.jpg"
                      alt="Diagram 6"
                      width={600}
                      height={400}
                      className="img-fluid rounded shadow-sm"
                    />
                  </div>
                </div>

                <div className="text-center mt-5">
                  <Link href="/eg/assignments" className="btn btn-info text-white">
                    Back to Assignments
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <footer className="bg-light py-3 mt-5">
        <div className="container text-center">
          <p className="mb-0">All rights reserved. © Copyright 2023.</p>
        </div>
      </footer>
    </>
  );
}